---
- name: Create users playbook
  hosts: all
  vars_files:
  - vars/users.yml
  tasks:
  - name: Create users
    become: yes
    user:
      name: "{{ item.login }}"
      password: "{{ item.password }}"
      update_password: on_create
    loop: "{{ users }}"
  - name: Print passwords
    debug:
      msg: "{{ item.login }} - {{ item.password | password_hash('sha512') }}"
    loop: "{{ users }}"
...
